# Generated by Django 5.0.7 on 2024-07-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiller', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profil',
            options={'verbose_name_plural': 'Profiller'},
        ),
        migrations.AlterModelOptions(
            name='profilstate',
            options={'verbose_name_plural': 'Profil Statement'},
        ),
        migrations.AlterField(
            model_name='profil',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profil_images/%Y/%m/'),
        ),
    ]
